# Book config for Zenn
# See: https://zenn.dev/zenn/articles/book-guide

title: "ニコ生ゲーム入門"
summary: "README と BASIC、MULTI フォルダの内容をまとめたチュートリアル"
topics: ["niconico", "akashic"]
price: 0
published: false
chapters:
  - readme
  - 1-minimal
  - 2-game
  - 3-scene
  - 4-entity
  - 5-label
  - 6-asset
  - 7-sprite
  - 8-audio
  - 9-event
  - 10-update
  - 11-onJoin
  - 12-global_event
  - 19-skip
  - 99-username
